# Generated by Django 4.2.1 on 2023-06-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_data.category'),
        ),
    ]
