# Generated by Django 4.2.1 on 2023-06-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='webpage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
