# Generated by Django 4.2.1 on 2023-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0006_data_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
