# Generated by Django 4.2.1 on 2023-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0007_data_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
