# Generated by Django 4.2.1 on 2023-06-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0011_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
