# Generated by Django 4.2.1 on 2023-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0012_data_is_bookmarked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='tag',
            field=models.ManyToManyField(to='scrap_data.tage'),
        ),
    ]
