# Generated by Django 4.2.1 on 2023-06-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0013_tage_data_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tage',
            new_name='Tags',
        ),
    ]
