# Generated by Django 4.2.1 on 2023-06-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0014_rename_tage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='tag',
            field=models.ManyToManyField(blank=True, to='scrap_data.tags'),
        ),
    ]
