# Generated by Django 4.2.1 on 2023-06-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0015_alter_data_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourite'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
    ]
