# Generated by Django 4.2.1 on 2023-06-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0016_alter_favourite_options_alter_tags_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='is_bookmarked',
        ),
    ]
