# Generated by Django 4.2.1 on 2023-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0018_toolsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsubmit',
            name='interested',
            field=models.BooleanField(default=False),
        ),
    ]
