# Generated by Django 4.2.1 on 2023-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0020_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
