# Generated by Django 4.2.1 on 2023-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0021_news_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='webpage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
