# Generated by Django 4.2.1 on 2023-06-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0022_alter_news_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
