# Generated by Django 4.2.1 on 2023-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0023_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news-images/'),
        ),
    ]
