# Generated by Django 4.2.1 on 2023-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0024_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('webpage', models.CharField(blank=True, max_length=500, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
