# Generated by Django 4.2.1 on 2023-06-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0025_research'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='description',
            new_name='subject',
        ),
    ]
